---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
labels:
  maintainer: "Bastian Trompetter <wilier-humor7e@icloud.com>"
  org.opencontainers.image.authors: "Bastian Trompetter <wilier-humor7e@icloud.com>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Add-on: Mein Grafana-Loki"
  org.opencontainers.image.url: https://github.com/Frogy 76/home-assistant-addons
  org.opencontainers.image.source: https://github.com/Frogy 76/home-assistant-addons/Loki Addon
  org.opencontainers.image.documentation: https://github.com/Frogy 76/home-assistant-addons/Loki Addon/README.md
  org.opencontainers.image.created: "2025-04-15"
  org.opencontainers.image.version: 1.0.0
