---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
labels:
  maintainer: "BITTE_ERSETZEN <BITTE_ERSETZEN>"
  org.opencontainers.image.authors: "BITTE_ERSETZEN <BITTE_ERSETZEN>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Add-on: Mein Grafana-Loki"
  org.opencontainers.image.url: https://github.com/BITTE_ERSETZEN/home-assistant-addons
  org.opencontainers.image.source: https://github.com/BITTE_ERSETZEN/home-assistant-addons/mein-grafana-loki
  org.opencontainers.image.documentation: https://github.com/BITTE_ERSETZEN/home-assistant-addons/mein-grafana-loki/README.md
  org.opencontainers.image.created: "2025-04-15"
  org.opencontainers.image.version: 1.0.0
