---
build_from:
  aarch64: "ghcr.io/hassio-addons/debian-base:7.8.2"
  amd64: "ghcr.io/hassio-addons/debian-base:7.8.2"
  armv7: "ghcr.io/hassio-addons/debian-base:7.8.2"
labels:
  maintainer: "Bastian Trompetter <wilier-humor7e@icloud.com>"
  org.opencontainers.image.authors: "Bastian Trompetter <wilier-humor7e@icloud.com>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Add-on: Grafana Loki"
  org.opencontainers.image.url: "https://github.com/Frogy76/Loki-Addon"
  org.opencontainers.image.source: "https://github.com/Frogy76/Loki-Addon/loki-addon"
  org.opencontainers.image.documentation: "https://github.com/Frogy76/Loki-Addon/blob/main/loki-addon/README.md"
  org.opencontainers.image.created: "2025-04-15"
  org.opencontainers.image.version: "1.0.0"
