---
name: "Grafana Loki"
version: "1.0.0"
slug: "loki-addon"
description: |
  Grafana Loki ist ein horizontal skalierbares, hochverfügbares, mandantenfähiges Log-Aggregationssystem, inspiriert von Prometheus
arch:
  - aarch64
  - amd64
image: "ghcr.io/frogy76/ha-addons-loki-{arch}"
startup: system
url: "https://github.com/frogy76/Loki-Addon"
init: false
ports:
  3100/tcp: 3100
ports_description:
  3100/tcp: Loki listen port
panel_icon: mdi:router-network
map:
  - config
  - share
options:
  days_to_keep: 30
  log_level: info
schema:
  days_to_keep: int(1,)?
  config_path: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?