---
name: "Grafana Loki"
version: "1.0.6"
slug: "loki-addon"
description: |
  Grafana Loki is a horizontally scalable, highly available, multi-tenant log aggregation system inspired by Prometheus
arch:
  - aarch64
  - amd64
# Temporarily comment out the image parameter and use BUILD_FROM
# image: "ghcr.io/frogy76/ha-addons-loki-{arch}"
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
startup: system
url: "https://github.com/frogy76/Loki-Addon"
init: false
ports:
  3100/tcp: 3100
ports_description:
  3100/tcp: Loki listen port
panel_icon: mdi:router-network
map:
  - config
  - share
options:
  days_to_keep: 30
  log_level: info
  resource_limits:
    memory: "256M"
    cpu_percent: 50
  security:
    enable_auth: false
    username: "admin"
    password: ""
  advanced:
    max_chunk_size: "1048576"
    max_query_series: 500
    max_query_lookback: "720h"
schema:
  days_to_keep: int(1,)?
  config_path: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  resource_limits:
    memory: str?
    cpu_percent: int(10,100)?
  security:
    enable_auth: bool?
    username: str?
    password: password?
  advanced:
    max_chunk_size: str?
    max_query_series: int(0,10000)?
    max_query_lookback: str?
