auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: warn

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /data/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /data/loki/chunks

pattern_ingester:
  enabled: true
limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  discover_service_name:
    [
      service,
      app,
      application,
      app_name,
      name,
      app_kubernetes_io_name,
      container,
      container_name,
      k8s_container_name,
      component,
      workload,
      job,
      k8s_job_name,
    ]
  discover_log_levels: true
